apiVersion: e1bv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: expense
spec:
  serviceRef:
    name: frontend
    port: 80
  targetGroupARN: {{ .Values.tgb.arn }}
  targetType: ip